---
title: "Homework 5"
author: "Cydney Jardine"
date: "11/28/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(broom)
library(dlnm)
library(stats)
library(knitr)
library(scales)
library(lubridate)
```

##Input dataset
```{r input data}
library(readr)
homicide_data <- read_csv("~/Desktop/Homework5/data/homicide-data.csv")
```

```{r city_state}
#new column combining state and city; filter to baltimore
baltimore <- homicide_data %>%
  mutate(city_name = str_c(city, state, sep = ",")) %>%
  filter(city_name == "Baltimore,MD")
```

##Baltimore data
```{r baltimore}
baltimore1 <- baltimore %>%
  mutate(Date = ymd(reported_date))
```

##Making year-month to group by later
```{r per month}
per_month <- baltimore1 %>%
  group_by(year(Date), month(Date)) %>%
  mutate(New_Date = str_c(`year(Date)`, '-', `month(Date)`))
```

##Defining summer and winter months
```{r months}
per_month1 <- per_month %>%
  mutate(Weather = `month(Date)` %in% 5:10)

per_month1 <- per_month1 %>%
  mutate(Weather = factor(Weather, levels = c(TRUE, FALSE),
                          labels = c("Summer", "Winter")))
```

```{r permonth}
per_month2 <- per_month1 %>%
  select(Date, Weather, New_Date) %>%
  group_by(New_Date) %>%
  mutate(Total = n()) %>%
  distinct(New_Date, .keep_all = TRUE)
```

```{r plot1, fig.width= 12, fig.height= 3}

vline <- "2015-04-12"

##Build graph
per_month2 %>%
ggplot(aes(x = Date, y = Total)) +
  geom_bar(aes(fill = Weather), stat = "identity", width = 35) +
  scale_fill_manual(values = c("grey", "lightblue")) +
  geom_smooth(se = FALSE, span = 0.1) +
  geom_vline(aes(xintercept = as.numeric(as.Date(vline))),
             linetype = 3, col = "red", size = 1) +
  annotate("text", x = per_month$Date[1700], y = 41 - 0.1,
           label = "Arrest of \n Freddie Gray", color = "darkgrey") +
  theme_dark() +
  theme(legend.position = "bottom")
```